[package]
name = "gears-cli"
version = "0.1.2"
authors = ["Michiel Kalkman <michiel@nosuchtype.com>"]
description = "Gears CLI tool"
documentation = "https://docs.rs/xflow"
homepage = "https://github.com/gears-project/gears-cli"
repository = "https://github.com/gears-project/gears-cli.git"
readme = "README.md"
keywords = ["gears"]
categories = []
license = "MIT"

[dependencies]
gears = "0.1.2"
log = "0.3"
env_logger = "0.4"

[dependencies.clap]
version = "~2.25.0"
default-features = false
features = [ "suggestions", "color", "wrap_help" ]

[replace]
# "gears:0.1.2" = { path = "/home/michiel/dev/github/gears-core-rust" }
"gears:0.1.2" = { git = 'https://github.com/gears-project/gears-core-rust' }


